name: Build and deploy Node.js app to Azure Web App - insureflow

on:
  push:
    branches:
      - feature/frontend_azure_deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: apps/web

      - name: Build Next.js app
        run: npm run build
        working-directory: apps/web

      - name: Prepare standalone output
        run: |
          mkdir -p standalone-deploy/.next/static
          cp -r .next/standalone/* standalone-deploy/
          cp -r .next/static/* standalone-deploy/.next/static
          cp -r public standalone-deploy/public || true
          cp package.json standalone-deploy/
        working-directory: apps/web

      - name: Zip deployment package
        run: zip -r release.zip .
        working-directory: apps/web/standalone-deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: apps/web/standalone-deploy/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: deploy

      - name: Unzip artifact to deploy folder
        run: unzip deploy/release.zip -d deploy/app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'insureflow'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D8E94B03F7134D30BE4F581FD70EC6C3 }}
          package: deploy/app