name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - feature/azure-functions-email-intake
  workflow_dispatch:

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: apps/azure_functions
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Deploy Azure Function using publish profile
        uses: azure/functions-action@v1
        with:
          app-name: insureflow-func
          package: apps/azure_functions
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_697A070FDF244857A0D1D8896A1F6CCE }}